### ISSUE TITLE
Symlink

### ISSUE THREAD

**Issue by magicdawn** [AsaAyers/js-hyperclick-core#4]
## case

![image](https://cloud.githubusercontent.com/assets/4067115/24319351/75d0b11e-1154-11e7-91b1-574b1b7bc6a1.png)

demo project: https://github.com/magicdawn/tiz-demo/

## intent

avoid `../../`

## phenomenon

hyperclick jump to the symlink file, so I can open the file twice

![image](https://cloud.githubusercontent.com/assets/4067115/24319374/ff4f80d2-1154-11e7-89c6-6f17fb512eeb.png)

![image](https://cloud.githubusercontent.com/assets/4067115/24319376/05eb542a-1155-11e7-8577-75155054ab33.png)

## related

node-resolve does not support symlink yet 
https://github.com/substack/node-resolve/issues/122

**Comment by AsaAyers** [comment]
When a file is resolved through a symlinked folder, atom opens the file with the symlink path instead of the actual path to the file. This can leave you with two tabs that point to the same file. Correct?

Why do you have two PRs? What different things are they addressing? What is the use case for keeping the current behavior / why do we need a setting?

**Comment by magicdawn** [comment]
1. yes
2. two PR, when using useRealpath, if the Realpath is out of current project, the editor and the treeview looks strange. And node has perserveSymlink command option, I just thought maybe someone need the old behavior. and in my case I do need the Realpath, so I take that option as configurable. And it's OK with me to set useRealpath to true and unconfigurable.
